version: '3.7'

services:
    whoami:
        image: "containous/whoami"
        container_name: whoami
        networks:
            - traefik
            - internal
        depends_on:
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.backend=whoami"
            - "traefik.http.routers.whoami.entryPoints=http, https"
            - "traefik.http.routers.whoami.rule=Host(`whoami.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.whoami.tls=true"
            - "traefik.http.routers.whoami.tls.certResolver=cloudflare"
            - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_traefik"
            - "traefik.http.services.whoami.loadbalancer.server.port=80"
