version: '3.7'

services:
    dnscrypt:
        image: dnscrypt
        container_name: dnscrypt
        volumes:
            - "./data/dnscrypt-proxy:/etc/dnscrypt-proxy"
            - "./dnscrypt-proxy/dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml"
        networks:
            dns:
                ipv4_address: 172.16.238.2
