version: '3.7'

services:
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        ports:
            # Used for DNS.
            - "53:53/tcp"
            # Used for DNS.
            - "53:53/udp"
        environment:
            ServerIP: "172.16.238.3"
            TZ: 'America/Los_Angeles'
            DNSSEC: "false"
            DNS1: "172.16.238.2#5300"
            DNS2: "172.16.238.2#5300"
            IPv6: "false"
            VIRTUAL_HOST: "pihole-alt1.${TRAEFIK_DOMAIN}"
            VIRTUAL_PORT: "80"
            PROXY_LOCATION: "pihole"
            WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
            BLOCKINGMODE: "NXDOMAIN"
        volumes:
            - './data/pihole/etc/pihole:/etc/pihole'
            - './data/pihole/dnsmasq.d:/etc/dnsmasq.d'
            - './pihole/02-dnscrypt.conf:/etc/dnsmasq.d/02-dnscrypt.conf'
            - './pihole/03-local.conf:/etc/dnsmasq.d/03-local.conf'
        dns:
            - 127.0.0.1
            - 1.1.1.1
        networks:
            # External for downloading block lists, etc.
            external:
            dns:
                ipv4_address: 172.16.238.3
            traefik:
        depends_on:
            - dnscrypt
            - traefik
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.backend=pihole-alt1"
            - "traefik.http.routers.pihole-alt1.entryPoints=http, https"
            - "traefik.http.routers.pihole-alt1.rule=Host(`pihole-alt1.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.pihole-alt1.tls=true"
            - "traefik.http.routers.pihole-alt1.tls.certResolver=cloudflare"
            - "traefik.http.routers.pihole-alt1.middlewares=pihole-alt1"
            - "traefik.http.middlewares.pihole-alt1.addprefix.prefix=/admin"
            - "traefik.http.services.pihole-alt1.loadbalancer.server.port=80"
            - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_traefik"
