[http]
  [http.routers]
    [http.routers.https-only]
      entryPoints = ["http"]
      middlewares = ["httpsredirect"]
      rule = "HostRegexp(`{host:.+}`)"
      service = "noop"
    [http.routers.pihole]
      entryPoints = ["http", "https"]
      middlewares = ["pihole"]
	  rule = "Host(`pihole.ericlagergren.com`)"
	  service = "pihole"
	  [http.routers.pihole.tls]
	    certResolver = "cloudflare"
	[http.routers.printer]
	  entryPoints = ["http", "https"]
	  rule = "Host(`printer.ericlagergren.com`)"
	  service = "printer"
	  [http.routers.printer.tls]
	    certResolver = "cloudflare"

  [http.services]
    [http.services.noop.loadBalancer]
      [[http.services.noop.loadBalancer.servers]]
        url = "http://127.0.0.1"
    [http.services.pihole.loadbalancer]
	  [[http.services.pihole.loadbalancer.servers]]
	    url = "http://dns1.ericlagergren.com:80"
	[http.services.printer.loadbalancer]
	  [[http.services.printer.loadbalancer.servers]]
	    url = "https://prnt1.ericlagergren.com"

  [http.middlewares]
    [http.middlewares.httpsredirect.redirectScheme]
      scheme = "https"
    [http.middlewares.pihole.addprefix]
	  prefix = "/admin"
