version: '3.7'

services:
    kapacitor:
        container_name: kapacitor
        image: kapacitor:latest
        volumes:
            - "./data/kapacitor/var/lib/kapacitor:/var/lib/kapacitor"
            - "./data/kapacitor/etc/kapacitor:/etc/kapacitor"
            - "./kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf"
        networks:
            - internal
        restart: unless-stopped
