version: '3.7'

services:
    telegraf:
        image: telegraf:latest
        container_name: telegraf
        environment:
            HOSTNAME: "telegraf"
            HOST_PROC: /rootfs/proc
            HOST_SYS: /rootfs/sys
            HOST_ETC: /rootfs/etc
            HOST_VAR: /rootfs/var
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "/proc:/rootfs/proc:ro"
            - "/sys:/rootfs/sys:ro"
            - "/etc:/rootfs/etc:ro"
            - "/var:/rootfs/var:ro"
            - "./data/telegraf/var/lib/telegraf:/var/lib/telegraf"
            - "./data/telegraf/etc/telegraf:/etc/telegraf"
            - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf"
        networks:
            - internal
        depends_on:
            - influxdb
        restart: unless-stopped
