version: '3.7'

services:
    influxdb:
        image: arm32v7/influxdb:latest
        container_name: influxdb
        volumes:
            - "./data/influxdb/var/lib/influxdb:/var/lib/influxdb"
            - "./data/influxdb/etc/influxdb:/etc/influxdb"
            - "./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf"
        networks:
            - internal
        restart: unless-stopped
